name: telepad
description: Teleportation pads for the Spigot API 1.20
author: meclondrej
version: 1.2.1
api-version: 1.21.4
main: cz.meclondrej.telepad.Plugin
commands:
  telepad:
    description: Controls telepads
    usage: /<command> <subcommand>
permissions:
  telepad.create:
    description: Allows creation of telepads
    default: op
  telepad.remove:
    description: Allows removal of telepads
    default: op
  telepad.list:
    description: Allows listing of telepads
    default: true
  telepad.ring:
    description: Allows usage of telepads
    default: true
  telepad.save:
    description: Allows manual config file saving
    default: op
  telepad.connect:
    description: Allows remote usage of telepads
    default: op
  telepad.id:
    description: Allows identification of a telepad
    default: true
  telepad.id.local:
    description: Allows identification of a local telepad
    default: true
  telepad.id.remote:
    description: Allows identification of a remote telepad
    default: true
